
on:
  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [[ $file == *.txt ]]; then
              echo "$file was changed"
              echo "$(dirname "${file}")"
              echo "$(cd "$(dirname "$file")" && pwd -P)/$(basename "$file")"
              echo "$(cd "$(dirname "$file")" && pwd -P)"
              echo "$(cd "$(dirname "$file")")"
              echo "this is the file name"
              echo "$(basename "$file")"
              echo "ends file name"
              cd $(cd "$(dirname "$file")" && pwd -P)
              cat "$(basename "$file")"
              #Installing jupyter & regex
              #python -m pip install jupyter
              #python -m pip install regex
              #echo "Hello there" > file1.txt
              ls
            fi
          done
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo "this is the message1"
          git status
          echo "this is the message2"
          git add .
          #git commit -a -m 'creating a file'
          git diff --quiet && git diff --staged --quiet || git commit -am 'Added license headers'
          git push origin main -f
