
on:
  #push:
    #branches:
      #- main
  #pull_request:
    #branches:
      #- main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23

      - name: List all changed files
        run: |
          echo "${{ steps.changed-files.outputs.all_changed_files }}"
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            if [ "$file" = "*.txt" ]; then
              echo "$file was changed"
              echo "$(dirname "${file}")"
              echo "$(cd "$(dirname "$file")" && pwd -P)/$(basename "$file")"
              echo "$(cd "$(dirname "$file")" && pwd -P)"
              cd $(cd "$(dirname "$file")" && pwd -P)
              echo "Hello world" > file1.txt
              ls
            fi
          done
          
      - name: Configure Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          echo "this is the message"
          git status
          echo "this is the message"
          git add .
          git commit -Af -m 'creating a file'
          git push origin main -f
