# Building my own actions workflow
# To check the python installation

on:
  workflow_dispatch:
  
#on:
  #push:
    #branches:
      #- main
  
jobs:
  build_wheel:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Build wheel and install
        run: |
          python -m pip install --user --upgrade build
          python -m pip install jupyter
          python -m pip install pandas
          python -m pip install numpy
          python -m  pip install matplotlib
          python -m build
          find ./dist/*.whl | xargs pip install
          
      - name: Run Script
        run: |
          jupyter nbconvert --execute --to markdown README.ipynb
          
      - name: Configure Git
        run: |
          git config user.email "joseantoniotv91@gmail.com"
          git config user.name "testus3"
          git add -f ./dist/*.whl
          git commit -m 'pushing new wheel'
          git push origin main
