on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.
          
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v23

      - name: List all changed files
        run: |
          ls .
          #count=`ls -1 *.py 2> /dev/null | wc -l`
          #echo $count
          
          #if [[ `ls -1 *.py 2> /dev/null | wc -l` == 2 ]]; then
          if [[ $(ls .) == *.ipynb; then
            #python -m pip install jupyter
            #python -m pip install regex
            echo "ipynb file found"
          fi
